language: sh

before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install shellcheck

script:
  - shellcheck aliases exports bin/*

notifications:
  email: false

branches:
  only:
    - master
