language: sh

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
  - shellcheck bootstrap.sh config_image.sh genconfig_image.sh laptop.local bin/*

notifications:
  email: false

branches:
  only:
    - master
