language: sh

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y shellcheck

script:
  - shellcheck aliases exports bin/*

notifications:
  email: false

branches:
  only:
    - master
