#!/usr/bin/env bash

alias zip='zip -9'
alias abc='cd ~/code/ruby/gitlab.activeby.net/activebilling/core'
alias f='git ls-files | grep'
alias 'rds!'='rake db:setup'
alias gdc='git diff --cached'
alias updatedb='/usr/libexec/locate.updatedb'
alias ba='bundle add'
alias bsl='brew services list'
alias bs='brew services'
