#!/usr/bin/env bash

export RI="--format ansi"

export PATH="$HOME/.bin:$HOME/bin:$PATH"

export PATH="/usr/local/sbin:$PATH"

export PATH="$PATH:/usr/local/lib/node_modules"

# shellcheck disable=SC2155
export PATH="$PATH:$(yarn global bin)"

# The sqlite formula is keg-only, which means it was not symlinked
# into /usr/local, because macOS provides an older sqlite3.
export PATH="/usr/local/opt/sqlite/bin:$PATH"

if [[ ! -d "$HOME/.nvm" ]]; then
  mkdir ~/.nvm
fi
export NVM_DIR="$HOME/.nvm"

# `brew --prefix nvm` is slow
# `nvm` is extremely slow at startup: https://github.com/creationix/nvm/issues/1277
# shellcheck disable=SC1091
source "/usr/local/opt/nvm/nvm.sh" --no-use

# `brew --prefix formula` is slow
export RUBY_CONFIGURE_OPTS
RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl --with-readline-dir=/usr/local/opt/readline"

eval "$(keychain --eval --agents gpg --quiet)"

unset DOCKER_TLS_VERIFY
unset DOCKER_CERT_PATH
unset DOCKER_MACHINE_NAME
unset DOCKER_HOST

# shellcheck disable=SC1090
source ~/.github_token
