# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mgutz"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(rbenv git bundler rails cake coffee capistrano)

source $ZSH/oh-my-zsh.sh

# User configuration

if [[ $OSTYPE == darwin* ]]; then
  export PATH="$HOME/.bin:$PATH"

  # recommended by brew doctor
  export PATH="/usr/local/bin:$PATH"

  export PATH="$PATH:/usr/local/lib/node_modules"
  source $(brew --prefix nvm)/nvm.sh

  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init - --no-rehash zsh)"
fi

if [[ $OSTYPE == linux* ]]; then
  # Add RVM to PATH for scripting
  PATH=$PATH:$HOME/.rvm/bin

  PATH=$PATH:/usr/local/heroku/bin

  # Go workspace location
  export GOPATH=$HOME/gocode
  PATH=$PATH:$GOPATH/bin
  PATH=$PATH:/usr/local/go/bin

  export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/

  export M2_HOME=/usr/local/apache-maven/apache-maven-3.1.1
  export M2=$M2_HOME/bin
  # Add the MAVEN_OPTS environment variable to specify JVM properties, e.g.
  # export MAVEN_OPTS="-Xms256m -Xmx512m".
  # This environment variable can be used to supply extra options to Maven.
  PATH=$PATH:$M2

  PATH=$PATH:/usr/local/texlive/2013/bin/x86_64-linux
  PATH=$PATH:/opt/ActiveTcl-8.5/bin
  export PATH=$PATH:$HOME/elixir-0.15.1/bin

  export CATALINA_HOME=/opt/apache-tomcat-8.0.9
fi

export RI="--format ansi"
export DISABLE_SPRING=true

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

if [[ $OSTYPE == linux* ]]; then
  distro=$(awk -F= '/^NAME/{print $2}' /etc/os-release)

  if [[ $distro == "Ubuntu" ]]; then
    # If not running interactively, do not do anything
    case $- in *i*)
      [[ -z "$TMUX" ]] && exec tmux -2
    esac
  fi

  # https://github.com/sstephenson/rbenv/issues/616
  if [[ $distro == "Gentoo" ]]; then
    unset RUBYOPT
  fi
fi

if [[ $OSTYPE == darwin* ]]; then
  if which jenv > /dev/null; then
    # Enable shims and autocompletion
    eval "$(jenv init -)"

    # Use Homebrew's directories rather than ~/.jenv
    # export JENV_ROOT=/usr/local/opt/jenv
  fi

  source ~/.github_token
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  if [[ $OSTYPE == darwin* ]]; then
    export EDITOR='mvim'
  else
    export EDITOR='gvim'
  fi
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias zip='zip -9'
alias abc='cd code/ruby/gitlab.activeby.net/activebilling/core'
