# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="mgutz"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rvm)

source $ZSH/oh-my-zsh.sh

# If not running interactively, do not do anything
# [[ $- != *i* ]] && return
case $- in *i*)
  [[ -z "$TMUX" ]] && exec tmux -2
esac

# Customize to your needs...

alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias bo='bundle open'
alias spk='thunar ~/.config/sublime-text-3/Packages'
alias zip='zip -9'

# Add RVM to PATH for scripting
PATH=$PATH:$HOME/.rvm/bin

# Go workspace location
export GOPATH=$HOME/gocode
PATH=$PATH:$GOPATH/bin
PATH=$PATH:/usr/local/go/bin

export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/

export M2_HOME=/usr/local/apache-maven/apache-maven-3.1.1
export M2=$M2_HOME/bin
# Add the MAVEN_OPTS environment variable to specify JVM properties, e.g.
# export MAVEN_OPTS="-Xms256m -Xmx512m".
# This environment variable can be used to supply extra options to Maven.
PATH=$PATH:$M2

PATH=$PATH:/usr/local/texlive/2013/bin/x86_64-linux
PATH=$PATH:/opt/ActiveTcl-8.5/bin
export PATH=$PATH:$HOME/elixir-0.15.1/bin

export CATALINA_HOME=/opt/apache-tomcat-8.0.9

export EDITOR=subl

export RI="--format ansi"
export DISABLE_SPRING=true
